# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Event-Planner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Event-Planner
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'lottie-ios'
  pod 'SkeletonView'
  pod 'Parse'
  pod 'MessageInputBar'
  
  target 'Event-PlannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Event-PlannerUITests' do
    # Pods for testing
  end

end
